version: '3.4'

services:
  backend:
    image: ${DOCKER_REGISTRY-}backend
    build:
      context: .
      dockerfile: src/MoviesApp/Dockerfile
    ports:
      - 3000
  frontend:
    image: ${DOCKER_REGISTRY-}frontend
    build:
      context: .
      dockerfile: src/MoviesApp/Dockerfile
    ports:
      - 4000
