# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      step-function-arn:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Step function arn'
        # Default value if no value is explicitly provided
        default: 'arn:aws:states:us-east-1:769184580875:stateMachine:HelloWorld'
        # Input has to be provided for the workflow to run
        required: true
      step-function-flag:
        description: 'Something flag to pass to the step function'
        default: true
        required: true
      test-scenario:
        type: choice
        description: Choose which scenario to run
        options:
        - retention
        - purchase
        - acquisition

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  trigger-step-function:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Execute Step Function
      run: |
        aws stepfunctions start-execution \
        --state-machine-arn ${{ github.event.inputs.step-function-arn }} \
        --input "{ \
          \"IsHelloWorldExample\": ${{ github.event.inputs.step-function-flag }},\
          \"Scenario\": \"${{ github.event.inputs.test-scenario }}\" \
        }"
